name: 02-basics-first-workflow

on: 
  # pull_request:
  #     types:
  #       - closed
  push:
    branches:
      - main


      

jobs:
  print-hello-world22:
    runs-on: ubuntu-latest
    steps:
      - name: Print Hello World
        run: echo "Hello, world!"
