name: 02-basics-first-workflow

on: 
  # pull_request:
  #     types:
  #       - closed
  push:
    # branches:
    #   - main
    # branches-ignore:
    #   - main
    # tags:
    #   - v1
    # tags-ignore:
    #   - v1

    paths:
      - "routes/web.php"







      

jobs:
  print-hello-world22:
    runs-on: ubuntu-latest
    steps:
      - name: Print Hello World
        run: echo "Hello, world!"
