name: 04-basics-first-workflow

on: 
  schedule:
    - cron: "*/5 * * * *"

jobs:
  print-hello-world22:
    runs-on: ubuntu-latest
    steps:
      - name: Print Hello World
        run: echo "Hello, world!"
