name: 05-basics-context
run-name: "Hello ${{ github.actor }}. ${{ github.run_number }}" 

env:
  PR_NUMBER: ${{ github.event.pull_request.number }}
  NAME: 'GDGK5'
on: push
    

jobs:
  print-context-data:
    runs-on: ubuntu-latest
    steps:
      - name: Print context data1
        run: echo $NAME
