name: 05-basics-context
run-name: "Hello ${{ github.actor }}. ${{ github.run_number }}"

on: [push, pull_request]

env:
  PR_NUMBER: ${{ github.event.pull_request.number }}
  NAME: 'GDGK5'

jobs:
  print-context-data:
    runs-on: ubuntu-latest
    steps:
      - name: Print context data
        run: |
          echo ${{ vars.JO }}
          echo ${{ env.PR_NUMBER }}
         
