name: 05-basics-context
run-name: "Hello ${{ github.actor }}. ${{ github.run_number }}" 
on: 
  workflow_dispatch

jobs:
  print-context-data:
    runs-on: ubuntu-latest
    steps:
      - name: Print context data
        run: echo "${{ toJSON(github) }}"
