name: 05-basics-context
run-name: "Hello ${{ github.actor }}"
on: 
  workflow_dispatch

jobs:
  print-context-data:
    runs-on: ubuntu-latest
    steps:
      - name: Print context data
        run: echo "${{ toJSON(github) }}"
