name: 06 Basics Context
run-name: ${{ github.actor }} Explaining context data - Try Number ${{ github.run_number }}

on: 
  workflow_dispatch

jobs:
  print-context-data:
    runs-on: ubuntu-latest
    steps:
      - name: Print Context Data
        # run: echo ${{ github }}
        # run: echo ${{ github.actor }}
        # run: echo ${{ github['actor'] }}
        # run: echo ${{ github.event_name }}
        # run: echo ${{ job.status }}
        # run: echo ${{ toJson(github) }}
        run: echo ${{ toJson(github.event) }}
