name: 15 containers
run-name: ${{ github.actor }} Explaining containers - Try Number ${{ github.run_number }}

on: 
  workflow_dispatch

jobs:
  php-versions:
    runs-on: ubuntu-latest
    container:
      image: php:7.4 #the name of image in docker hub or the one you created
    steps:
      - name: Check PHP version
        run: php -v