name: 15 containers
run-name: ${{ github.actor }} Explaining containers - Try Number ${{ github.run_number }}

on: 
  workflow_dispatch

jobs:
  Build:
    runs-on: ubuntu-latest
    steps:
      - name: Setup PHP
        uses: nanasess/setup-php@v4
        with:
          php-version: 7.4
      - run: php -v