name: 15 services
run-name: ${{ github.actor }} Explaining services - Try Number ${{ github.run_number }}

on: 
  workflow_dispatch

jobs:
  redis-job:
    runs-on: ubuntu-latest
    services:
      redis: #you have to give name of service unlike container as you can have more than one service
        image: redis:latest
    steps:
      - name: Setup redis
        run: |
          sudo apt-get install redis -y
          sudo service redis-server start
      - name: Check redis
        run: redis-cli ping