name: 15 gh achtions
run-name: ${{ github.actor }} Explaining services - Try Number ${{ github.run_number }}

on: 
  workflow_dispatch

jobs:
  print-hello-world22:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4.2.2
      - name: gh
        run: gh issue create --title "Hello World from GH Actions" --body "This is a test issue created from a GitHub Actions workflow."
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}