name: Example 06 - run tests with coverage
run-name: Example 06 - run tests with coverage

on: 
  pull_request
  #workflow_dispatch

jobs:
  run-tests:
    runs-on: ubuntu-latest

    services:
      mysql:
        image: mysql:latest
        env:
          MYSQL_DATABASE: github_actions_course
          MYSQL_ALLOW_EMPTY_PASSWORD: yes
        ports:
          - 3306:3306
        options: >
          --health-cmd="mysqladmin ping"
          --health-interval=10s
          --health-timeout=5s
          --health-retries=3

    steps:
      - name: Checkout Code
        uses: actions/checkout@v4.2.2

      # - name: Install PHP & Composer (IF YOU WANT)
      
      - name: Install project dependencies
        run: composer install -q
      
      - name: Prepare project
        run: |
          cp .env.example .env
          php artisan key:generate
      
      - name: Run migrations
        run: php artisan migrate
      
      - name: Run tests
        run: XDEBUG_MODE=coverage php artisan test --coverage --coverage-text