name: 15 services
run-name: ${{ github.actor }} Explaining services - Try Number ${{ github.run_number }}

on: 
  workflow_dispatch

jobs:
  print-hello-world22:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Print Hello World
        uses: ./.github/actions/print-hello-world
