name: 14 Basics Matrix
run-name: ${{ github.actor }} Explaining Matrix - Try Number ${{ github.run_number }}

on: 
  workflow_dispatch

jobs:
  Build:
    runs-on: ${{ matrix.os }}
    strategy:
      max-parallel: 2
      matrix:
        os: [ubuntu-latest, windows-latest]
        php_version: [8.2, 8.3, 8.4]
        exclude: 
          - os: ubuntu-latest
            php_version: 8.3
        include: 
          - os: macos-latest
            php_version: 8.4
    steps:
      - name: Build Project
        run: echo "Build Project on Operating System (${{ matrix.os }}) with php version (${{ matrix.php_version }})"
