name: 15 Basics Runners
run-name: ${{ github.actor }} Explaining Runners - Try Number ${{ github.run_number }}

on: 
  workflow_dispatch

jobs:
  Build:
    runs-on: [self-hosted, Windows, X64, runner1]
    steps:
      - name: Print Hello World
        run: echo "Hello World"
