name: 17 Basics Container
run-name: ${{ github.actor }} Explaining Container - Try Number ${{ github.run_number }}

on: 
  workflow_dispatch

jobs:
  php-version:
    runs-on: ubuntu-latest
    
    container:
      image: php:7.2

    steps:
      - name: Check PHP Version
        run: php -v
